const SampleContent = `
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut auctor faucibus tincidunt. Nunc aliquet eros tortor, vitae consectetur risus interdum ut. Duis eget elit molestie, fringilla ipsum quis, ornare sem. Praesent ut diam nisi. Maecenas suscipit, ex a vehicula laoreet, sapien tortor eleifend quam, vitae condimentum sapien mi in ligula. Etiam viverra tristique nunc et hendrerit. Aenean eleifend interdum diam, quis sagittis tellus mollis sit amet. Nunc efficitur augue massa, vel porta leo hendrerit vitae. Nunc consequat ipsum sed nisi ornare, vel fringilla ante rhoncus. Morbi pharetra luctus odio, id ornare massa cursus non. Nullam ultricies euismod lectus, in sollicitudin est euismod id. Curabitur purus ante, egestas at venenatis suscipit, pellentesque eget tellus. Praesent eget nunc lacinia, bibendum enim vel, ullamcorper sem. Aliquam dolor metus, interdum sed magna eu, interdum rutrum nulla. Pellentesque a pellentesque mi, sit amet convallis nisl.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut auctor faucibus tincidunt. Nunc aliquet eros tortor, vitae consectetur risus interdum ut. Duis eget elit molestie, fringilla ipsum quis, ornare sem. Praesent ut diam nisi. Maecenas suscipit, ex a vehicula laoreet, sapien tortor eleifend quam, vitae condimentum sapien mi in ligula. Etiam viverra tristique nunc et hendrerit. Aenean eleifend interdum diam, quis sagittis tellus mollis sit amet. Nunc efficitur augue massa, vel porta leo hendrerit vitae. Nunc consequat ipsum sed nisi ornare, vel fringilla ante rhoncus. Morbi pharetra luctus odio, id ornare massa cursus non. Nullam ultricies euismod lectus, in sollicitudin est euismod id. Curabitur purus ante, egestas at venenatis suscipit, pellentesque eget tellus. Praesent eget nunc lacinia, bibendum enim vel, ullamcorper sem. Aliquam dolor metus, interdum sed magna eu, interdum rutrum nulla. Pellentesque a pellentesque mi, sit amet convallis nisl.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut auctor faucibus tincidunt. Nunc aliquet eros tortor, vitae consectetur risus interdum ut. Duis eget elit molestie, fringilla ipsum quis, ornare sem. Praesent ut diam nisi. Maecenas suscipit, ex a vehicula laoreet, sapien tortor eleifend quam, vitae condimentum sapien mi in ligula. Etiam viverra tristique nunc et hendrerit. Aenean eleifend interdum diam, quis sagittis tellus mollis sit amet. Nunc efficitur augue massa, vel porta leo hendrerit vitae. Nunc consequat ipsum sed nisi ornare, vel fringilla ante rhoncus. Morbi pharetra luctus odio, id ornare massa cursus non. Nullam ultricies euismod lectus, in sollicitudin est euismod id. Curabitur purus ante, egestas at venenatis suscipit, pellentesque eget tellus. Praesent eget nunc lacinia, bibendum enim vel, ullamcorper sem. Aliquam dolor metus, interdum sed magna eu, interdum rutrum nulla. Pellentesque a pellentesque mi, sit amet convallis nisl.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut auctor faucibus tincidunt. Nunc aliquet eros tortor, vitae consectetur risus interdum ut. Duis eget elit molestie, fringilla ipsum quis, ornare sem. Praesent ut diam nisi. Maecenas suscipit, ex a vehicula laoreet, sapien tortor eleifend quam, vitae condimentum sapien mi in ligula. Etiam viverra tristique nunc et hendrerit. Aenean eleifend interdum diam, quis sagittis tellus mollis sit amet. Nunc efficitur augue massa, vel porta leo hendrerit vitae. Nunc consequat ipsum sed nisi ornare, vel fringilla ante rhoncus. Morbi pharetra luctus odio, id ornare massa cursus non. Nullam ultricies euismod lectus, in sollicitudin est euismod id. Curabitur purus ante, egestas at venenatis suscipit, pellentesque eget tellus. Praesent eget nunc lacinia, bibendum enim vel, ullamcorper sem. Aliquam dolor metus, interdum sed magna eu, interdum rutrum nulla. Pellentesque a pellentesque mi, sit amet convallis nisl.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut auctor faucibus tincidunt. Nunc aliquet eros tortor, vitae consectetur risus interdum ut. Duis eget elit molestie, fringilla ipsum quis, ornare sem. Praesent ut diam nisi. Maecenas suscipit, ex a vehicula laoreet, sapien tortor eleifend quam, vitae condimentum sapien mi in ligula. Etiam viverra tristique nunc et hendrerit. Aenean eleifend interdum diam, quis sagittis tellus mollis sit amet. Nunc efficitur augue massa, vel porta leo hendrerit vitae. Nunc consequat ipsum sed nisi ornare, vel fringilla ante rhoncus. Morbi pharetra luctus odio, id ornare massa cursus non. Nullam ultricies euismod lectus, in sollicitudin est euismod id. Curabitur purus ante, egestas at venenatis suscipit, pellentesque eget tellus. Praesent eget nunc lacinia, bibendum enim vel, ullamcorper sem. Aliquam dolor metus, interdum sed magna eu, interdum rutrum nulla. Pellentesque a pellentesque mi, sit amet convallis nisl.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut auctor faucibus tincidunt. Nunc aliquet eros tortor, vitae consectetur risus interdum ut. Duis eget elit molestie, fringilla ipsum quis, ornare sem. Praesent ut diam nisi. Maecenas suscipit, ex a vehicula laoreet, sapien tortor eleifend quam, vitae condimentum sapien mi in ligula. Etiam viverra tristique nunc et hendrerit. Aenean eleifend interdum diam, quis sagittis tellus mollis sit amet. Nunc efficitur augue massa, vel porta leo hendrerit vitae. Nunc consequat ipsum sed nisi ornare, vel fringilla ante rhoncus. Morbi pharetra luctus odio, id ornare massa cursus non. Nullam ultricies euismod lectus, in sollicitudin est euismod id. Curabitur purus ante, egestas at venenatis suscipit, pellentesque eget tellus. Praesent eget nunc lacinia, bibendum enim vel, ullamcorper sem. Aliquam dolor metus, interdum sed magna eu, interdum rutrum nulla. Pellentesque a pellentesque mi, sit amet convallis nisl.
`

export default SampleContent
